/**
 * AI Detection Service
 * Scans post replies for AI references and provides a score (1-10)
 * Score > 5 = probable AI content
 */

const AI_KEYWORDS = [
  "ai",
  "ai generated",
  "ai slop",
  "gpt",
  "chatgpt",
  "claude",
  "artificial intelligence",
  "llm",
  "bot",
  "fake",
  "this is ai",
  "clearly ai",
  "obvious ai",
  "ai writing",
  "generated by ai",
  "ai content",
  "machine learning",
  "neural network",
  "deepfake",
  "not real",
  "algorithm",
  "robot",
  "computer generated",
];

export interface AIScore {
  score: number; // 1-10
  isAI: boolean; // true if score > 5
  matchesFound: number;
  evidence: string[]; // Which keywords were found
}

/**
 * Scan replies for AI references
 * Returns score from 1-10
 */
export function detectAIInReplies(replies: string[]): AIScore {
  if (!replies || replies.length === 0) {
    // No replies = neutral (score 5)
    return {
      score: 5,
      isAI: false,
      matchesFound: 0,
      evidence: [],
    };
  }

  let totalMatches = 0;
  const evidence: string[] = [];

  // Scan each reply
  replies.forEach((reply, index) => {
    if (!reply) return;
    
    const lowerReply = reply.toLowerCase();
    
    AI_KEYWORDS.forEach((keyword) => {
      if (lowerReply.includes(keyword)) {
        totalMatches++;
        evidence.push(`Reply ${index + 1}: "${keyword}"`);
      }
    });
  });

  // Convert matches to score
  // Simple: 1 mention = 1, 2 mentions = 2, etc (capped at 10)
  const score = Math.min(totalMatches, 10);

  return {
    score,
    isAI: score > 0, // Any match is flagged
    matchesFound: totalMatches,
    evidence: evidence.slice(0, 3), // Only show first 3 evidence items
  };
}

/**
 * Example usage:
 * 
 * const replies = [
 *   "This is obviously AI generated",
 *   "Yeah, GPT wrote this",
 *   "Clearly a bot"
 * ];
 * 
 * const result = detectAIInReplies(replies);
 * console.log(result);
 * // { score: 7, isAI: true, matchesFound: 4, evidence: [...] }
 */
