import { FeedItem } from "../utils/types";

const AI_KEYWORDS = [
  "ai generated",
  "ai slop",
  "gpt",
  "chatgpt",
  "claude",
  "artificial intelligence",
  "llm",
  "bot",
  "fake",
  "this is ai",
  "clearly ai",
  "obvious ai",
  "ai writing",
  "generated by ai",
  "ai content",
  "machine learning",
  "neural network",
  "deep fake",
];

export interface AISlop Detection {
  score: number;
  evidence: string[];
  confidence: "low" | "medium" | "high";
  commentsChecked: number;
  matchesFound: number;
}

export interface AIFilterSettings {
  enabled: boolean;
  sensitivity: number;
  whitelist: WhitelistRule[];
}

export interface WhitelistRule {
  type: "author" | "hashtag";
  value: string;
  reason: string;
}

export function detectAISlopFromComments(
  comments: string[]
): AISlop Detection {
  const firstTen = comments.slice(0, 10);
  let matches = 0;
  const evidence: string[] = [];

  firstTen.forEach((comment, index) => {
    const lowerComment = comment.toLowerCase();

    AI_KEYWORDS.forEach((keyword) => {
      if (lowerComment.includes(keyword)) {
        matches++;
        evidence.push(`Comment ${index + 1}: "${keyword}"`);
      }
    });
  });

  const maxPossible = Math.min(firstTen.length * 5, 50);
  const score = Math.min((matches / maxPossible) * 100, 100);

  let confidence: "low" | "medium" | "high";
  if (score > 60) {
    confidence = "high";
  } else if (score > 30) {
    confidence = "medium";
  } else {
    confidence = "low";
  }

  return {
    score: Math.round(score),
    evidence,
    confidence,
    commentsChecked: firstTen.length,
    matchesFound: matches,
  };
}

export function getSensitivityThreshold(sensitivity: number): number {
  return 10 + sensitivity * 0.8;
}

export function shouldWhitelist(
  post: FeedItem,
  rules: WhitelistRule[]
): boolean {
  return rules.some((rule) => {
    if (rule.type === "author") {
      const handle = rule.value.startsWith("@") 
        ? rule.value.slice(1) 
        : rule.value;
      return post.authorHandle === handle;
    }

    if (rule.type === "hashtag") {
      const hashtag = rule.value.startsWith("#") 
        ? rule.value 
        : `#${rule.value}`;
      return post.text.toLowerCase().includes(hashtag.toLowerCase());
    }

    return false;
  });
}

export interface FeedItemWithAIScore extends FeedItem {
  aiScore?: number;
  aiEvidence?: string[];
  aiConfidence?: "low" | "medium" | "high";
  aiFiltered?: boolean;
}

export async function fetchComments(
  postId: string,
  platform: string
): Promise<string[]> {
  return [];
}
